spring:
  application:
    name: alarm-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update
      hibernate:
        transaction:
          jta: platform:org.hibernate.service.jta.JtaPlatform


  datasource:
    url: jdbc:mysql://localhost:3306/dayeyak
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#
#  server:
#    port: 8080
#
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:19090/eureka



#  âœ¨ feat	     í•´ë‹¹ íŒŒì¼ì— ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ ìƒê¹€
#  ğŸ‰ add	     ì—†ë˜ íŒŒì¼ì„ ìƒì„±í•¨, ì´ˆê¸° ì„¸íŒ…
#  ğŸ› fix	     ë²„ê·¸ ìˆ˜ì •
#  â™»ï¸ refactor	 ì½”ë“œ ë¦¬íŒ©í† ë§
#  ğŸšš move	     íŒŒì¼ ì˜®ê¹€/ì •ë¦¬
#  ğŸ”¥ delete	   ê¸°ëŠ¥/íŒŒì¼ ì‚­ì œ
#  âœ…Â test	     í…ŒìŠ¤íŠ¸ ì½”ë“œ ì‘ì„±
#  ğŸ™ˆ gitfix	   gitignore ìˆ˜ì •
#  ğŸ”¨Â script	   build.gradle ë³€ê²½, docker compose ë³€ê²½
#  ğŸ“Â chore	   ì£¼ì„ ì¶”ê°€ ë° ìˆ˜ì •, ë³€ìˆ˜ëª… ë° í´ë˜ìŠ¤ëª… ìˆ˜ì •
#  âš¡ï¸Â improve	 ê°œì„ 
